# accounts/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView


urlpatterns = [
    path('base/', views.base, name='base'),
    path('video/', views.video_view, name='video'),
    path('photos/', views.photos_view, name='photos'),
    path('objectives/', views.objectives_view, name='objectives'),
    path('moa/', views.moa_view, name='moa'),
    path('login/', views.login_view, name='login'),
    path('super-admin-dashboard/', views.super_admin_view, name='super_admin_dashboard'),
    path('campus-admin-dashboard/', views.campus_admin_view, name='campus_admin_dashboard'),
    path('staff-extensionist-dashboard/', views.staff_extensionist_view, name='staff_extensionist_dashboard'),
    path('department-coordinator-dashboard/', views.department_coordinator_view, name='department_coordinator_dashboard'),
    path('extensionist-dashboard/', views.extensionist_view, name='extensionist_dashboard'),
    path('permission-denied/', TemplateView.as_view(template_name='accounts/permission_denied.html'), name='permission_denied'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('register/department-coordinator/', views.register_department_coordinator, name='register_department_coordinator'),
    path('register/extensionist/', views.register_extensionist, name='register_extensionist'),
    path('department-coordinators/', views.list_department_coordinators, name='department_coordinators_list'),
    path('extensionists/', views.list_extensionists, name='extensionists_list'),
    path('super_admin/', views.super_admin_view, name='super_admin'),
    path('campus_admin/', views.campus_admin_view, name='campus_admin'),
    path('staff_extensionist/', views.staff_extensionist_view, name='staff_extensionist'),
    path('department_coordinator/', views.department_coordinator_view, name='department_coordinator'),
    path('extensionist/', views.extensionist_view, name='extensionist'),
    path('permission_denied/', views.permission_denied, name='permission_denied'),
    path('upload/', views.upload_document, name='upload_document'),
    path('pending/', views.pending_documents, name='pending_documents'),
    path('recommended/', views.recommended_documents, name='recommended_documents'),
    path('rejected/', views.rejected_documents, name='rejected_documents'),
    path('completed/', views.completed_documents, name='completed_documents'),
    path('recommend/<int:doc_id>/', views.recommend_document, name='recommend_document'),
    path('approve/<int:doc_id>/', views.approve_document, name='approve_document'),
    path('reject/<int:doc_id>/', views.reject_document, name='reject_document'),
    path('complete/<int:document_id>/', views.completion_upload, name='completion_upload'),
    path('documents/', views.document_list, name='document_list'),
    path('document/<int:document_id>/', views.view_document, name='view_document'),
    path('documents/completion/pending/', views.completion_pending_documents, name='completion_pending_documents'),
    path('documents/completion/recommended/', views.completion_recommended_documents, name='completion_recommended_documents'),
    path('documents/<int:doc_id>/completion/recommend/', views.recommend_completion, name='recommend_completion'),
    path('documents/<int:doc_id>/completion/reject/', views.reject_completion, name='reject_completion'),
    path('documents/<int:doc_id>/completion/approve/', views.approve_completion, name='approve_completion'),
    path('chat/list/', views.document_chat_list, name='document_chat_list'),
    path('chat/fetch/<int:document_id>/', views.fetch_chat_messages, name='fetch_chat_messages'),
    path('chat/send/<int:document_id>/', views.post_chat_message, name='post_chat_message'),
    path('chat/mark-read/<int:document_id>/', views.mark_read_messages, name='mark_read_messages'),
    
    path('delete-coordinator/<int:user_id>/', views.delete_coordinator, name='delete_coordinator'),
    path('documents/ongoing/', views.ongoing_documents, name='ongoing_documents'),
    path('annual-reports/', views.list_annual_reports, name='list_annual_reports'),
    path('annual-reports/create/', views.create_annual_report, name='create_annual_report'),
    path('annual-reports/<int:report_id>/', views.view_report, name='view_report'),
    path('annual-reports/<int:report_id>/add-activity/', views.add_activity, name='add_activity'),
    path('annual-reports/<int:report_id>/pdf/', views.generate_pdf, name='generate_pdf'),
    path('annual-reports/<int:report_id>/linkage/add/', views.add_linkage, name='add_linkage'),
    path('reports/delete/<int:report_id>/', views.delete_report, name='delete_report'),
    path('quarterly-reports/create/', views.create_quarterly_report, name='create_quarterly_report'),
    path('quarterly-reports/<int:report_id>/', views.view_quarterly_report, name='view_quarterly_report'),
    path('quarterly-reports/<int:report_id>/add-project/', views.add_extension_project, name='add_extension_project'),
    path('quarterly-reports/<int:report_id>/pdf/', views.generate_quarterly_pdf, name='generate_quarterly_pdf'),
    path('quarterly-reports/delete/<int:report_id>/', views.delete_quarterly_report, name='delete_quarterly_report'),
    path('quarterly-reports/', views.list_quarterly_reports, name='list_quarterly_reports'),
    path('reorder-activities/', views.reorder_activities, name='reorder_activities'),
    path('update/', views.update_account, name='update_account'),
    path('change-password/', views.change_password, name='change_password'),
    path('report/<int:report_id>/edit/', views.edit_annual_report, name='edit_annual_report'),
    path('activity/<int:activity_id>/edit/', views.edit_activity, name='edit_activity'),
    path('linkage/<int:linkage_id>/edit/', views.edit_linkage, name='edit_linkage'),
    path('edit-quarterly-report/<int:report_id>/', views.edit_quarterly_report, name='edit_quarterly_report'),
    path('edit-extension-project/<int:project_id>/', views.edit_extension_project, name='edit_extension_project'),
    path('archived-documents/', views.archived_documents, name='archived_documents'),
    path('hierarchy/', views.user_hierarchy_view, name='user_hierarchy'),
    path('delete_user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('edit-user/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('documents/<int:doc_id>/need-revision/', views.need_revision_document, name='need_revision_document'),
    path('extensionists/delete/<int:user_id>/', views.delete_extensionist, name='delete_extensionist'),
    path('media/upload/', views.media_upload, name='media_upload'),
    path('media/<int:pk>/edit/', views.media_edit, name='media_edit'),
    path('media/<int:pk>/delete/', views.media_delete, name='media_delete'),
    
    path('api/albums/<int:album_id>/photos/', views.album_photos_api, name='album_photos_api'),
    path("albums/<int:album_id>/upload/", views.photo_upload, name="photo_upload"),
    path('albums/upload/', views.album_upload, name='album_upload'),
    # urls.py
    path('albums/<int:album_id>/edit/', views.edit_album, name='album_edit'),
    path('photos/<int:photo_id>/edit/', views.edit_photo, name='photo_edit'),
    path("album/delete/<int:album_id>/", views.delete_album, name="delete_album"),
    path("photo/delete/<int:photo_id>/", views.delete_photo, name="delete_photo"),
    path('template-list', views.template_list, name='template_list'),
    path('upload-template/', views.template_upload, name='template_upload'),
    path('edit/<int:pk>/', views.template_edit, name='template_edit'),
    path('template-delete/<int:pk>/', views.template_delete, name='template_delete'), 

    path("daytraining-reports/quarters/", views.quarterly_report_list, name="quarterly_report_list"),
    path("daytraining-reports/quarters/<str:quarter>/<int:year>/", views.quarterly_reports_detail, name="quarterly_reports_detail"),
    path(
        "daytraining-reports/quarters/<str:quarter>/<int:year>/open/",
        views.open_day_training_reports,
        name="open_day_training_reports",
    ),
    path(
        "daytraining-reports/quarters/<str:quarter>/<int:year>/download/",
        views.download_day_training_reports_excel,
        name="download_day_training_reports_excel",
    ),
    path('upload-moa/', views.upload_moa, name='upload_moa'),
    path('delete-moa/<int:moa_id>/', views.delete_moa, name='delete_moa'),
    path('edit-moa/<int:moa_id>/', views.edit_moa, name='edit_moa'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)