# Generated by Django 5.0.6 on 2025-11-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_daytrainingentry_number_of_days_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('DCS', 'DCS (IT-CS)'), ('DMS (HM)', 'DMS (HM)'), ('DMS (BM)', 'DMS (BM)'), ('DC', 'DC (Criminology)'), ('DAS', 'DAS (Psychology)'), ('DTE', 'DTE (Education)')], max_length=100),
        ),
    ]
