# Generated by Django 5.0.6 on 2025-11-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_alter_department_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOAResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='moa_logos/')),
                ('pdf_file', models.FileField(upload_to='moa_pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
