# Generated by Django 5.0.6 on 2025-11-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_moaresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytrainingentry',
            name='related_curricular_offering',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
