# Generated by Django 5.0.6 on 2025-11-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_galleryimage_alter_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowcaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showcase/')),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
