# Generated by Django 5.0.6 on 2025-11-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0081_showcaseimage_delete_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Campus Admin', 'Campus Coordinator'), ('Staff Extensionist', 'Staff Extensionist'), ('Department Coordinator', 'Department Coordinator'), ('Extensionist', 'Extensionist')], max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('completion_processing', 'Completion Reviewing'), ('completion_recommended', 'Completion Recommended')], default='pending', max_length=30, null=True),
        ),
    ]
