# Generated by Django 5.0.6 on 2025-11-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0082_alter_customuser_account_type_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Campus Admin', 'Campus Extension Coordinator'), ('Staff Extensionist', 'Staff Extensionist'), ('Department Coordinator', 'Department Coordinator'), ('Extensionist', 'Extensionist')], max_length=50),
        ),
    ]
