# Generated by Django 5.0.6 on 2025-12-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Super Admin', 'Campus Dean'), ('Campus Admin', 'Campus Extension Coordinator'), ('Staff Extensionist', 'Staff Extensionist'), ('Department Coordinator', 'Department Coordinator'), ('Extensionist', 'Extensionist')], max_length=50),
        ),
    ]
