# Generated by Django 5.0.6 on 2025-12-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0085_document_activity_proposal_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytrainingreport',
            name='title',
        ),
    ]
