# Generated by Django 5.0.6 on 2026-01-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_documentfilehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoalbum',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
