# Generated by Django 5.0.6 on 2026-05-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_documentrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('DCS', 'DCS (IT-CS)'), ('DMS_HM', 'DMS (HM)'), ('DMS_BM', 'DMS (BM)'), ('DC', 'DC (Criminology)'), ('DAS', 'DAS (Psychology)'), ('DTE', 'DTE (Education)')], max_length=100),
        ),
    ]
